split -l 4000 -d Mahouka_Koukou_no_Rettousei_1_-_Enrollment_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_1_-_Enrollment_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_10_-_Visitor_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_10_-_Visitor_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_11_-_Visitor_[III]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_11_-_Visitor_[III]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_12_-_Double_Seven_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_12_-_Double_Seven_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_13_-_Steeplechase_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_13_-_Steeplechase_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_14_-_Ancient_City_Insurrection_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_14_-_Ancient_City_Insurrection_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_15_-_Ancient_City_Insurrection_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_15_-_Ancient_City_Insurrection_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_16_-_Yotsuba_Succession_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_16_-_Yotsuba_Succession_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_17_-_Master_Clans_Conference_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_17_-_Master_Clans_Conference_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_18_-_Master_Clans_Conference_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_18_-_Master_Clans_Conference_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_19_-_Master_Clans_Conference_[III]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_19_-_Master_Clans_Conference_[III]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_2_-_Enrollment_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_2_-_Enrollment_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_20_-_Southern_Sea_Riot_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_20_-_Southern_Sea_Riot_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_21_-_Prologue_of_Disturbance_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_21_-_Prologue_of_Disturbance_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_22_-_Prologue_of_Disturbance_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_22_-_Prologue_of_Disturbance_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_23_-_Isolation_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_23_-_Isolation_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_24_-_Escape_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_24_-_Escape_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_25_-_Escape_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_25_-_Escape_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_26_-_Invasion_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_26_-_Invasion_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_27_-_Sudden_Change_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_27_-_Sudden_Change_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_3_-_Nine_Schools_Competition_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_3_-_Nine_Schools_Competition_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_4_-_Nine_Schools_Competition_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_4_-_Nine_Schools_Competition_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_5_-_Summer_Holiday_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_5_-_Summer_Holiday_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_6_-_Yokohama_Disturbance_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_6_-_Yokohama_Disturbance_[I]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_7_-_Yokohama_Disturbance_[II]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_7_-_Yokohama_Disturbance_[II]_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_8_-_Reminiscence_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_8_-_Reminiscence_[Satou_Tsutomu].txt
split -l 4000 -d Mahouka_Koukou_no_Rettousei_9_-_Visitor_[I]_[Satou_Tsutomu].txt Mahouka_Koukou_no_Rettousei_9_-_Visitor_[I]_[Satou_Tsutomu].txt
